"""Transcendence-complexity analysis for ψ-trees over F_0.

This module implements an empirical test of the following hypothesis,
introduced in response to the failure of the (ord, leading) uniqueness
induction at depth 5 (see commit 7c34f491, ``docs/sheffer_analysis.md``):

    Hypothesis (transcendence invariant).
    For every non-constant g ∈ F_0 at depth ≤ d, the composition
    ``ψ(ψ(g, g), ψ(g, g))`` introduces at least one new algebraic atom
    ``sinh(·)`` or ``arsinh(·)`` whose argument is transcendental over
    the field generated by the atoms of all trees in F_0 at depth ≤ d.

If the hypothesis holds, the "transcendence complexity" tc(f) — defined
as the minimum number of algebraically-independent atoms needed to
express f over ℚ(x) — is strictly increasing with ψ-depth, which would
close the Pure-sinh Non-representability Lemma at every depth.

The experiment proceeds as follows.

1. Enumerate all unbranched ψ-trees of depth ≤ D over the terminal set
   {1, x}, up to the semantic equivalence detected by SymPy.
2. For each tree, compute a high-precision Taylor series at x = 0 and
   extract the "atom signature" — the multiset of leading coefficients
   of every sinh / arsinh nested inside the expression.
3. For every pair (f_depth, f_depth+1), test whether the depth-(d+1)
   tree introduces a novel atom signature that is provably algebraically
   independent of all atom signatures at depth ≤ d, using
   numerical transcendence tests (PSLQ via ``mpmath.pslq``) at 150 digits.

The test is not a proof — PSLQ with a fixed precision can only rule out
algebraic dependencies of bounded degree and coefficient size. A negative
PSLQ result at 150 digits with degree up to 8 and integer coefficients
up to 10^12 is a strong empirical argument for independence.
"""

from __future__ import annotations

import itertools
from dataclasses import dataclass, field
from typing import List, Tuple

import mpmath as mp
import sympy as sp


mp.mp.dps = 150


@dataclass
class AtomSignature:
    """Numerical fingerprint of a ψ-tree expression at x = x0.

    Holds the value of the tree together with the values of every
    internal ``sinh(·)`` and ``arsinh(·)`` subexpression at a fixed
    numerical point. Two trees whose signatures agree at N evaluation
    points are considered plausibly equal; a PSLQ call with their
    values attempts to detect a non-trivial rational relation.
    """
    value: mp.mpf
    atoms: Tuple[mp.mpf, ...] = ()
    depth: int = 0
    expression: str = ""


def psi(x: sp.Expr, y: sp.Expr) -> sp.Expr:
    """Symbolic evaluation of ψ(x, y) = sinh(x) − arsinh(y)."""
    return sp.sinh(x) - sp.asinh(y)


def enumerate_psi_trees(depth: int, terminals: Tuple[sp.Expr, ...]) -> List[sp.Expr]:
    """Enumerate all ψ-trees of exact depth ``depth`` over ``terminals``.

    For depth 0 the trees are the terminals themselves. For depth d > 0
    every tree has the form ψ(l, r) with l, r trees of depth ≤ d−1 and
    at least one of them of depth exactly d−1 (so that the overall depth
    is exactly d).
    """
    if depth == 0:
        return list(terminals)
    subtrees_by_depth: dict[int, list[sp.Expr]] = {0: list(terminals)}
    for d in range(1, depth + 1):
        subtrees_by_depth[d] = []
        lower = [t for dd in range(d) for t in subtrees_by_depth[dd]]
        same_minus_one = subtrees_by_depth[d - 1]
        for left, right in itertools.product(lower, same_minus_one):
            subtrees_by_depth[d].append(psi(left, right))
        for left, right in itertools.product(same_minus_one, lower):
            tree = psi(left, right)
            subtrees_by_depth[d].append(tree)
    return subtrees_by_depth[depth]


def _collect_atoms(expr: sp.Expr) -> List[sp.Expr]:
    """Return every sinh and arsinh subexpression in ``expr`` in
    post-order (innermost first). Used to compute the atom signature."""
    out: list[sp.Expr] = []

    def walk(e: sp.Expr) -> None:
        if e.is_Atom:
            return
        for arg in e.args:
            walk(arg)
        if e.func in (sp.sinh, sp.asinh):
            out.append(e)

    walk(expr)
    return out


def compute_atom_signature(
    expr: sp.Expr, x_sym: sp.Symbol, x0: float = 0.5, dps: int = 150
) -> AtomSignature:
    """Numerically evaluate the atom signature of ``expr`` at ``x0``."""
    old_dps = mp.mp.dps
    mp.mp.dps = dps
    try:
        value = mp.mpf(sp.N(expr.subs(x_sym, sp.Float(x0, dps)), dps))
        atoms = tuple(
            mp.mpf(sp.N(a.subs(x_sym, sp.Float(x0, dps)), dps))
            for a in _collect_atoms(expr)
        )
    finally:
        mp.mp.dps = old_dps
    return AtomSignature(value=value, atoms=atoms, expression=str(expr))


def transcendence_complexity(expr: sp.Expr, x_sym: sp.Symbol) -> int:
    """Number of distinct sinh / arsinh atoms in ``expr``.

    Two atoms that simplify to the same SymPy expression are counted once
    (``sp.simplify`` is applied before comparison). This is a *syntactic*
    proxy for true transcendence complexity: the real invariant is the
    algebraic transcendence degree of the atom set over ℚ(x), which is
    ≤ this count. The test below uses numerical PSLQ to flag atoms that
    do turn out to be algebraically dependent.
    """
    atoms = _collect_atoms(expr)
    seen: list[sp.Expr] = []
    for a in atoms:
        simplified = sp.simplify(a)
        if not any(sp.simplify(simplified - s) == 0 for s in seen):
            seen.append(simplified)
    return len(seen)


def test_pslq_independence(
    signatures: List[AtomSignature],
    max_coeff: int = 10**10,
    tol_dps: int = 120,
) -> dict:
    """Run PSLQ on the union of atom values and report any integer
    relations found.

    Returns a dict with ``pslq_result`` (list of integer coefficients or
    ``None`` if no relation is detected) and ``all_atoms`` (the flat
    sequence of atom values passed to PSLQ). A non-trivial result means
    the atoms are numerically consistent with an algebraic dependence of
    bounded degree and coefficient size; a ``None`` result at 120 digits
    with ``max_coeff = 10**10`` is strong evidence for independence.
    """
    all_atoms: list[mp.mpf] = []
    for sig in signatures:
        all_atoms.extend(sig.atoms)
    if len(all_atoms) < 2:
        return {"pslq_result": None, "all_atoms": all_atoms, "reason": "too few atoms"}
    old_dps = mp.mp.dps
    mp.mp.dps = tol_dps + 30
    try:
        relation = mp.pslq(all_atoms, tol=mp.mpf(10) ** (-tol_dps), maxcoeff=max_coeff)
    finally:
        mp.mp.dps = old_dps
    return {
        "pslq_result": list(relation) if relation is not None else None,
        "all_atoms": [float(a) for a in all_atoms],
    }


@dataclass
class TranscendenceTestReport:
    depth: int
    n_trees: int
    n_distinct_complexity: int
    max_complexity: int
    min_complexity: int
    complexity_increases_with_depth: bool
    pslq_check: dict = field(default_factory=dict)
    details: list = field(default_factory=list)


def run_transcendence_experiment(
    max_depth: int = 3,
    terminals: Tuple[sp.Expr, ...] = (sp.Integer(1), sp.Symbol("x")),
    x0: float = 0.5,
    max_trees_per_depth: int = 32,
) -> list[TranscendenceTestReport]:
    """Main experiment driver.

    Enumerates ψ-trees up to ``max_depth``, computes a transcendence-
    complexity score for each, and checks whether the score is strictly
    increasing in depth on at least the first ``max_trees_per_depth``
    trees per depth level.
    """
    x_sym = sp.Symbol("x")
    reports: list[TranscendenceTestReport] = []
    prior_max: int = -1
    for depth in range(max_depth + 1):
        trees = enumerate_psi_trees(depth, terminals)
        trees = trees[:max_trees_per_depth]
        complexities: list[int] = []
        signatures: list[AtomSignature] = []
        for tree in trees:
            c = transcendence_complexity(tree, x_sym)
            complexities.append(c)
            signatures.append(
                compute_atom_signature(tree, x_sym, x0=x0, dps=120)
            )
        this_max = max(complexities) if complexities else 0
        this_min = min(complexities) if complexities else 0
        n_distinct = len(set(complexities))
        increased = this_max > prior_max
        pslq = test_pslq_independence(signatures[:8], max_coeff=10**6, tol_dps=80)
        reports.append(
            TranscendenceTestReport(
                depth=depth,
                n_trees=len(trees),
                n_distinct_complexity=n_distinct,
                max_complexity=this_max,
                min_complexity=this_min,
                complexity_increases_with_depth=increased,
                pslq_check=pslq,
                details=[(str(t)[:80], c) for t, c in list(zip(trees, complexities))[:5]],
            )
        )
        prior_max = max(prior_max, this_max)
    return reports


if __name__ == "__main__":
    reports = run_transcendence_experiment(max_depth=3, max_trees_per_depth=16)
    print("\n=== Transcendence-complexity experiment ===")
    print(
        f"{'depth':>6s} {'n_trees':>8s} {'min_tc':>7s} {'max_tc':>7s} "
        f"{'distinct_tc':>12s} {'strictly_up':>12s}"
    )
    for r in reports:
        print(
            f"{r.depth:6d} {r.n_trees:8d} {r.min_complexity:7d} "
            f"{r.max_complexity:7d} {r.n_distinct_complexity:12d} "
            f"{str(r.complexity_increases_with_depth):>12s}"
        )
    print("\nSample expressions at max depth:")
    for expr_str, tc in reports[-1].details:
        print(f"  tc={tc}  {expr_str}")
    print("\nPSLQ check at max depth:")
    pslq = reports[-1].pslq_check
    print(f"  n_atoms={len(pslq.get('all_atoms', []))}")
    print(f"  relation found: {pslq.get('pslq_result')}")
