"""Last rung of the escalation ladder: streamed unranked verification.

For targets whose correct pair is generated by the inversion matching
but ranked past any feasible output cap (deep inside clamp-degenerate
match classes), ranking is the enemy: this pass verifies every
generated pair immediately, row by row, with no caps and no ordering.
Termination is guaranteed by exhaustion of the generated set; success
is guaranteed whenever the matching generates the pair at all.

Run after ``scripts.depth5_rescue``; merges per-target results into
``depth_wall_results.json`` under ``pool_streamed``.
"""

from __future__ import annotations

import json
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from eml_gam.benchmarks.depth_wall import (  # noqa: E402
    Verifier,
    make_grid,
    sample_critical_targets,
)
from eml_gam.canonical_pool import FunctionPool  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROW_CHUNK = 65_536
PER_RUN_CAP = 512


def stream_solve(pool: FunctionPool, ver: Verifier, y, depth: int,
                 time_budget_s: float = 2400.0) -> dict:
    k = depth - 1
    vecs = pool.stacked_vecs(k)
    M = vecs.shape[0]
    t0 = time.time()
    n_checked = 0
    for dec in (pool.decimals, 6, 5):
        for side in ("exp", "log"):
            for r0 in range(0, M, ROW_CHUNK):
                r1 = min(r0 + ROW_CHUNK, M)
                if side == "exp":
                    implied, valid = pool.implied_exp_children(y, vecs[r0:r1])
                else:
                    implied, valid = pool.implied_log_children(y, vecs[r0:r1])
                implied[~valid] = np.nan
                for off, members, _run_len in pool.match_row_runs(
                    implied, k, side, per_run_cap=PER_RUN_CAP, decimals=dec
                ):
                    other = r0 + off
                    for m in members:
                        pair = (m, other) if side == "exp" else (other, m)
                        n_checked += 1
                        if ver.check_pair(*pair):
                            return {
                                "recovered": True,
                                "seconds": time.time() - t0,
                                "n_checked": n_checked,
                                "decimals": dec,
                                "side": side,
                            }
                if time.time() - t0 > time_budget_s:
                    return {
                        "recovered": False,
                        "seconds": time.time() - t0,
                        "n_checked": n_checked,
                        "timeout": True,
                    }
    return {
        "recovered": False,
        "seconds": time.time() - t0,
        "n_checked": n_checked,
        "timeout": False,
    }


def main() -> None:
    path = os.path.join(ROOT, "depth_wall_results.json")
    with open(path) as f:
        data = json.load(f)
    ext = data["depths"]["5"].get("pool_extended", {})
    stubborn = [
        r["target"] for r in ext.get("per_target", []) if not r["recovered"]
    ]
    if not stubborn:
        print("no stubborn targets; nothing to do")
        return
    print(f"stubborn targets: {stubborn}")

    x = make_grid()
    pool = FunctionPool(x, operator="eml")
    pool.build(4)
    pool.compact()
    targets, _ = sample_critical_targets(pool, 5, 40, seed=1005)

    results = []
    for i in stubborn:
        nested = targets[i]
        y = pool.evaluate_nested(nested, pool.x[:, 0])
        ver = Verifier(pool, nested)
        res = {"target": i, **stream_solve(pool, ver, y, 5)}
        results.append(res)
        print(res, flush=True)

    data["depths"]["5"]["pool_streamed"] = {
        "per_target": results,
        "n_recovered": sum(r["recovered"] for r in results),
        "protocol": "unranked streamed verification, per-run cap "
                    f"{PER_RUN_CAP}, resolutions (8, 6, 5), 40 min budget",
    }
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
    print("merged pool_streamed into depth_wall_results.json")


if __name__ == "__main__":
    main()
